nitrogen*.conf: fix u-boot preferred provider
And switch to defconfig as now supported in v2017.07 release.

The missing virtual/bootloader variable was generating the following
error:
 $ bitbake u-boot-boundary
...
ERROR: Nothing PROVIDES 'u-boot-boundary'
u-boot-boundary was skipped: PREFERRED_PROVIDER_virtual/bootloader set to u-boot-fslc, not u-boot-boundary
u-boot-boundary was skipped: incompatible with machine nitrogen6x (not in COMPATIBLE_MACHINE)

Signed-off-by: Gary Bisson <gary.bisson@boundarydevices.com>
Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>
(cherry picked from commit 6146c7020a1d26d44ba59c13b3c7291a36fae2b4)